### ISSUE TITLE
Code appears to scan untracked files.

### ISSUE THREAD

**Issue by bellis-ai** [aws/aws-codeguru-cli#7]
**It appears that it was stuck scanning untracked package files from my filesystem**

I was testing out this tool in my local repository with a full scan before fully integrating it into the CICD pipeline. For some reason it was taking already over 1.5 hours to do a single scan (without completing), yet it only took less than 10 minutes when scanning the sample repo.

I recloned my local repo into a different folder (without having any packages installed or downloaded) and tried again. Took less than 10 minutes and completed successfully. huh.

I am now very worried what my up and coming cloud bill will look like.

**Please fix the tool so that it does not scan untracked (gitignore'd) files in the database, or at least warn of this behavior**

(Untracked files generally shouldn't exist if this is only used in a pipeline, but most certainly will affect those testing out the tool on their repo for the first time)

**Comment by martinschaef** [comment]
Thank you for reporting this! This is a very good point. If you specify a commit range, CodeGuru would only scan what's in the diff and you will not be billed for anything else. 
If you scan without a commit range, it uploads the entire folder and analyzes everything in there. So, this allows you to also scan folders that are not under version control.

What would be your preferred behavior? Should it respect the gitignore file automatically? Should it ask if it detects a gitignore file?

**Comment by bellis-ai** [comment]
I would think it would be most intuitive if untracked files are ignored by default, maybe with the option of including untracked as an extra CLI flag.

**Comment by martinschaef** [comment]
Yeah, that sounds reasonable. Let me put that on my backlog

**Comment by bellis-ai** [comment]
It just occurred to me that people who are scanning build files might also have those in their gitignore. Regardless be sure to make sure the documentation clearly describes this feature.

**Comment by martinschaef** [comment]
Since those are two separate uploads, this shouldn't be a problem. Only the source upload counts for billing. I started working on a release that asks if only files under version control should be analyzed, but I'll need a couple of days since I'm traveling.

**Comment by martinschaef** [comment]
Fwiw, you can take a look at pull request #10 which asks if you only want to scan files under version control. Feel free to comment and/or propose edits.
