### ISSUE TITLE
Dependent on Java to execute?

### ISSUE THREAD

**Issue by bellis-ai** [aws/aws-codeguru-cli#8]
It appears that java must be installed to run the released binary. Normally I'd expect a release to act as a standalone binary that doesn't require java to run, especially something which I need to put into a pipeline step.

If it must use java, this would be helpful to document in the README. 

It could also be helpful to create an image that could be used readily in a CICD pipeline (instead of downloading the binary).

**Comment by martinschaef** [comment]
Good point. Will add that. Thanks for pointing this out.
